// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1odoLrtANj6JCvpEms9ktbmV1HtJMdnQ',
    appId: '1:122897792889:android:64a90f6fe17f9332d1b9a8',
    messagingSenderId: '122897792889',
    projectId: 'news-app-1ebe2',
    storageBucket: 'news-app-1ebe2.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcWuICFSiEAdt0zqpRLaao2HUau50u18',
    appId: '1:122897792889:ios:9d07751dab27d6fcd1b9a8',
    messagingSenderId: '122897792889',
    projectId: 'news-app-1ebe2',
    storageBucket: 'news-app-1ebe2.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );


}
